"""Initial database setup

Revision ID: 382eaf159479
Revises: 
Create Date: 2025-09-01 20:46:41.507174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382eaf159479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotion_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('joy', sa.Float(), nullable=True),
    sa.Column('sadness', sa.Float(), nullable=True),
    sa.Column('anger', sa.Float(), nullable=True),
    sa.Column('fear', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_table('entry_tag',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_tag')
    op.drop_table('emotion_score')
    op.drop_table('entry')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
